{% set name = "prettypretty" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prettypretty-{{ version }}.tar.gz
  sha256: 3e8cd13920f381ee538dbfffa24f46b3aab758049985d6e152b5f32c385c98dc

build:
  skip: True  # [py<311]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python

test:
  imports:
    - prettypretty
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://apparebit.github.io/prettypretty/
  dev_url: https://github.com/apparebit/prettypretty
  doc_url: https://apparebit.github.io/prettypretty/python/
  summary: Applying 2020s color science to 1970s terminal user interfaces
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - thewchan
